##### 公共 配置 #######
#内置Tomcat容器配置
server:
  port: 80
  servlet:
    context-path:

#基础配置
spring:
  profiles:
    active: dev #选择配置分支，先读取系统环境变量，如果没有则默认值为 dev
  application:
    name: swcc
  #修改thymeleaf访问根路径
  thymeleaf:
    prefix: classpath:/view/
    cache: false
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  #mvc接收参数时对日期进行格式化
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: 106.53.125.170
    port: 5672
    username: sa
    password: 123456
    publisher-confirms: true
    virtual-host: /

  #jackson对响应回去的日期参数进行格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    show-sql: false


---
##### dev 配置 #######
spring:
  profiles: dev

  #数据库配置
  datasource:
    #url: jdbc:mysql://106.53.125.170:3306/cwc?serverTimezone=GMT%2B8&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    url: jdbc:mysql://localhost:3306/cwc?serverTimezone=GMT%2B8&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#是否需要输入验证码
captcha:
  enable: false

---
##### prod 配置 #######
spring:
  profiles: prod

  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/cwc?serverTimezone=GMT%2B8&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: ?{E,/s4D$AR8Zrk3
    driver-class-name: com.mysql.cj.jdbc.Driver

#是否需要输入验证码
captcha:
  enable: true

